application: mannirbot
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: numpy
  version: "1.6.1"
- name: block-io
  version: "1.1.6"
- name: hashlib
  version: "20081119"